python -u run_longExp.py       --random_seed 2023             --root_path ./dataset/       --data_path ETTm2.csv        --model GCformer       --data ETTm2       --features M       --enc_in 7       --enc_raw 7       --n_heads 16       --d_model 128       --d_ff 256       --head_dropout 0      --patch_len 16      --stride 8      --des 'Exp'       --train_epochs 100      --patience 2      --lradj 'TST'      --pct_start 0.4       --itr 1      --batch_size 32      --dropout 0.4      --fc_dropout 0.4   --global_bias 0.5 --local_bias 0.5  --seq_len 336       --context_len 336      --learning_rate 0.001      --pred_len 96  --h_channel 128  --h_token 512  --TC_bias 1  --norm_type 'seq_last'  --perturb_ratio 0.05   --decomposition 0  --global_model 'Gconv' --individual 1 --weight_decay 0.0001 

python -u run_longExp.py       --random_seed 2023             --root_path ./dataset/       --data_path ETTm2.csv    --model GCformer       --data ETTm2       --features M       --enc_in 7       --enc_raw 7       --n_heads 16       --d_model 128       --d_ff 256       --head_dropout 0      --patch_len 16      --stride 8      --des 'Exp'       --train_epochs 100      --patience 2      --lradj 'TST'      --pct_start 0.4       --itr 1      --batch_size 32      --dropout 0.4      --fc_dropout 0.4   --global_bias 0.5 --local_bias 0.5  --seq_len 336       --context_len 336      --learning_rate 0.001      --pred_len 192  --h_channel 128  --h_token 512  --TC_bias 1  --norm_type 'seq_last'  --perturb_ratio 0.05   --decomposition 0  --global_model 'Gconv' --individual 1 --weight_decay 0.0001 


python -u run_longExp.py       --random_seed 2023             --root_path ./dataset/       --data_path ETTm2.csv     --model GCformer       --data ETTm2       --features M       --enc_in 7       --enc_raw 7       --n_heads 16       --d_model 128       --d_ff 256       --head_dropout 0      --patch_len 16      --stride 8      --des 'Exp'       --train_epochs 100      --patience 5      --lradj 'TST'      --pct_start 0.4       --itr 1      --batch_size 32      --dropout 0.4      --fc_dropout 0.4   --global_bias 0.3 --local_bias 0.3  --seq_len 336       --context_len 336      --learning_rate 0.001      --pred_len 336  --h_channel 128  --h_token 512  --TC_bias 1  --norm_type 'seq_last'  --perturb_ratio 0.01   --decomposition 0  --global_model 'FNO' --individual 1 --weight_decay 0.0005 


python -u run_longExp.py       --random_seed 2023             --root_path ./dataset/       --data_path ETTm2.csv   --model GCformer       --data ETTm2       --features M       --enc_in 7       --enc_raw 7       --n_heads 16       --d_model 128       --d_ff 256       --head_dropout 0      --patch_len 16      --stride 8      --des 'Exp'       --train_epochs 100      --patience 3      --lradj 'TST'      --pct_start 0.4       --itr 1      --batch_size 32      --dropout 0.2      --fc_dropout 0.2   --global_bias 0.3 --local_bias 0.3  --seq_len 720       --context_len 336      --learning_rate 0.001      --pred_len 720  --h_channel 32  --h_token 1024  --TC_bias 1  --norm_type 'seq_last'  --perturb_ratio 0.01   --decomposition 0  --global_model 'Gconv' --individual 1 --weight_decay 0.0001 



