python -u run_longExp.py       --random_seed 2023              --root_path ./dataset/       --data_path traffic.csv      --model GCformer       --data custom       --features M   --c_out 862  --dec_in 862  --enc_in 862     --enc_raw 862       --n_heads 16       --d_model 128       --d_ff 256       --head_dropout 0      --patch_len 16      --stride 8      --des 'Exp'       --train_epochs 100      --patience 50      --lradj 'TST'      --pct_start 0.2      --itr 1      --batch_size 32      --learning_rate 0.001      --seq_len 336       --context_len 192       --pred_len 96       --dropout 0.4      --fc_dropout 0.4      --global_bias 0.5  --local_bias 0.5   --atten_bias 0.5  --TC_bias 1 --h_channel 1024   --norm_type 'revin'  --perturb_ratio 0  --weight_decay 0  --global_model 'Gconv' --h_token 512  --gpu 0 >logs/LongForecasting/traffic_GCformer_336_96_96.log

python -u run_longExp.py       --random_seed 2023              --root_path ./dataset/       --data_path traffic.csv     --model GCformer       --data custom       --features M   --c_out 862  --dec_in 862  --enc_in 862     --enc_raw 862       --n_heads 16       --d_model 128       --d_ff 256       --head_dropout 0      --patch_len 16      --stride 8      --des 'Exp'       --train_epochs 100      --patience 50      --lradj 'TST'      --pct_start 0.2      --itr 1      --batch_size 32      --learning_rate 0.001      --seq_len 336       --context_len 96       --pred_len 192       --dropout 0.4      --fc_dropout 0.4      --global_bias 0.5  --local_bias 0.5   --atten_bias 0.5  --TC_bias 1 --h_channel 1024   --norm_type 'revin'  --perturb_ratio 0  --weight_decay 0  --global_model 'Gconv' --h_token 512  --gpu 0 >logs/LongForecasting/traffic_GCformer_336_96_192.log



python -u run_longExp.py       --random_seed 2023              --root_path ./dataset/       --data_path traffic.csv       --model GCformer       --data custom       --features M   --c_out 862  --dec_in 862  --enc_in 862     --enc_raw 862       --n_heads 16       --d_model 128       --d_ff 256       --head_dropout 0      --patch_len 16      --stride 8      --des 'Exp'       --train_epochs 100      --patience 50      --lradj 'TST'      --pct_start 0.2      --itr 1      --batch_size 32      --learning_rate 0.001      --seq_len 336       --context_len 96       --pred_len 336       --dropout 0.4      --fc_dropout 0.4      --global_bias 0.5  --local_bias 0.5   --atten_bias 0.5  --TC_bias 1 --h_channel 1024   --norm_type 'revin'  --perturb_ratio 0  --weight_decay 0  --global_model 'Gconv' --h_token 512  --gpu 0 >logs/LongForecasting/traffic_GCformer_336_96_336.log 

python -u run_longExp.py       --random_seed 2023              --root_path ./dataset/       --data_path traffic.csv        --model GCformer       --data custom       --features M   --c_out 862  --dec_in 862  --enc_in 862     --enc_raw 862       --n_heads 16       --d_model 128       --d_ff 256       --head_dropout 0      --patch_len 16      --stride 8      --des 'Exp'       --train_epochs 100      --patience 50      --lradj 'TST'      --pct_start 0.2      --itr 1      --batch_size 32      --learning_rate 0.001      --seq_len 336       --context_len 192       --pred_len 720       --dropout 0.4      --fc_dropout 0.4      --global_bias 0.5  --local_bias 0.5   --atten_bias 0.5  --TC_bias 0 --h_channel 1024   --norm_type 'revin'  --perturb_ratio 0  --weight_decay 0  --global_model 'Gconv' --h_token 1024  --gpu 0 >logs/LongForecasting/traffic_GCformer_336_96_720.log




